name: Run Behave Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Install Chrome and ChromeDriver
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
        

    - name: Set up secrets as environment variables
      run: |
        export URL="${{ secrets.URL }}"
        export PASSWORD="${{ secrets.PASSWORD }}"
        export USER01="${{ secrets.USER01 }}"

    - name: Run Behave tests
      run: |
        behave ./features/teste.feature
